spring:
  config:
    import: optional:configserver:http://localhost:8888
  application:
    name: listing-service
  # jpa:
  #   database-platform: org.hibernate.dialect.PostgreSQLDialect
  #   hibernate:
  #     ddl-auto: validate
  #   show-sql: true
  #   properties:
  #     hibernate:
  #       format_sql: true
  #       jakarta.persistence.schema-generation.scripts.action: create
  #       jakarta.persistence.schema-generation.scripts.create-target: generated_schema.sql
